# --- Gemini CLI: Track Syncing Script ---
# This script automatically updates conductor/tracks.md with current git status for all projects.

$reposDir = "C:\Users\flori\source\repos"
$tracksFile = "$reposDir\conductor\tracks.md"

$header = @"
# 📊 Tracks Registry

This registry is automatically generated by `sync-tracks.ps1`.
All projects managed within this meta-workspace.

## 🚀 Active Tracks
"@

$tracks = @()
Get-ChildItem $reposDir -Directory | ForEach-Object {
    $repoPath = $_.FullName
    if (Test-Path "$repoPath\.git") {
        $name = $_.Name
        if ($name -eq "conductor") { return } # Skip conductor itself
        
        # Git Info
        $branch = git -C $repoPath rev-parse --abbrev-ref HEAD
        $lastCommit = git -C $repoPath log -1 --format="%ar"
        $status = if ((git -C $repoPath status --short).Count -gt 0) { "⚠️ (Uncommitted changes)" } else { "✅ (Clean)" }
        
        # Build Markdown Entry
        $entry = "- **[$name](../$name/index.md)**: Branch=$branch (Last commit $lastCommit) $status"
        $tracks += $entry
    }
}

$footer = @"

---
*Last Updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")*
"@

$content = $header + "`n" + ($tracks -join "`n") + "`n" + $footer
Set-Content -Path $tracksFile -Value $content -Encoding UTF8
Write-Host "✅ Tracks Registry updated in $tracksFile" -ForegroundColor Green
