using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NexusShell.Interfaces;
using NexusShell.Models;

namespace NexusShell.Services
{
    /// <summary>
    /// Implementation of the registry service that maintains the tracks.md documentation.
    /// </summary>
    public class RegistryService(NexusSettings settings) : IRegistryService
    {
        private readonly NexusSettings _settings = settings;

        /// <inheritdoc />
        public void UpdateRegistry(List<ProjectInfo> projects)
        {
            var tracksFile = Path.Combine(_settings.ConductorRoot, "tracks.md");
            
            var sb = new StringBuilder();
            sb.AppendLine("# 📊 Tracks Registry");
            sb.AppendLine();
            sb.AppendLine("This registry is automatically generated by the Nexus Command Center.");
            sb.AppendLine("All projects managed within this meta-workspace.");
            sb.AppendLine();
            sb.AppendLine("## 🚀 Active Tracks");

            foreach (var p in projects.OrderBy(p => p.Track).ThenBy(p => p.Name))
            {
                string status = p.HasChanges ? "⚠️ (Uncommitted changes)" : "✅ (Clean)";
                string remote = !string.IsNullOrEmpty(p.RemoteStatus) ? $" [blue]{p.RemoteStatus}[/]" : "";
                
                // Track Label
                string trackLabel = p.Track switch {
                    "SAAS" => "🌍 SaaS",
                    "LOCAL" => "🏗️ Local",
                    _ => "📂 Other"
                };

                sb.AppendLine($"- **[{p.Name}](../{p.Name}/index.md)** ({trackLabel}): Branch={p.Branch} {status}{remote}");
            }

            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine($"*Last Updated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");

            try {
                File.WriteAllText(tracksFile, sb.ToString(), Encoding.UTF8);
            } catch {
                // Ignore background write errors
            }
        }
    }
}
